feat: :sparkles: media with tags feat initial code
strandls/biodiv-resources pull request #43
Opened 2023-06-09 04:44 UTC by arunasd463

2023-09-25 13:59 UTC, prakhar-s requested changes

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/controllers/ResourceController.java
> +	@Path(ApiConstants.MEDIAGALLERY + ApiConstants.EDITPAGE + "/{mId}")
can you  make mId path param a little more descriptive?

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/controllers/ResourceController.java
> +			Long objId = Long.parseLong(mId);
rename objId to a more meaningful variable name.

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +	public MediaGalleryShow getMediaByID(Long objId) {
rename objId to a meaningful function parameter.

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/MediaGalleryHelper.java
> +						System.out.println(fileMap);
remove print statement

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/MediaGalleryHelper.java
> +						System.out.println(files);
remove print statement.

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/MediaGalleryHelper.java
> +
remove unnecessary spaces. Spaces may cause unnecessary merge conflicts.

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/MediaGalleryHelper.java
> +							mediaGalleryResourceDao.save(entity);
Is it possible to save all entities in a single DB call instead of one by one in for loop?

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +	public String uploadMedia(HttpServletRequest request, List<ResourceWithTags> resourceUpload) {
Can we change this function's return type to `createResourceMapping` function's type instead of a string

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +		return "Resource Uploaded Successfully";
return an output  instead of a success/failure message. Handle success/failure in frontend.

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +			List<Long> resourcesIds = mediaGalleryResourceDao.findByMediaId(mediaGallery.getId());
can we fetch this in bulk/one DB call instead of one-by-one in for loops?

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +		return new MediaGalleryListPageData(mediaGalleryDao.getTotalMediaGalleryCount(), mediaGalleryListTitles);
I think instead of getting count from a DB call (`mediaGalleryDao.getTotalMediaGalleryCount()`)  can't you get counts from  the length of `mediaGalleryListTitles` list?

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +					tagResourcesId = utilityServiceApi.getResourceIds(tags, context.toLowerCase(), "all");
need to verify this part of code. Ping me for this.

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +			return "Media Gallery Deleted Sucessfully";
is  it possible to  return  an output instead of a success string

2023-09-25 13:59 UTC, prakhar-s commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +	public String deleteMediaByID(HttpServletRequest request, Long mId) {
please remove all the extra spaces

2023-09-26 07:00 UTC, arunasd463 commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +	public MediaGalleryShow getMediaByID(Long objId) {
its a generic function hence naming it as object

2023-09-26 07:03 UTC, arunasd463 commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +		return new MediaGalleryListPageData(mediaGalleryDao.getTotalMediaGalleryCount(), mediaGalleryListTitles);
mediaGalleryListTitles is a paginated value

2023-09-26 07:08 UTC, arunasd463 commented on src/main/java/com/strandls/resource/services/Impl/ResourceServicesImpl.java
> +			return "Media Gallery Deleted Sucessfully";
Adding missiing try catches and returning null for failure

2023-10-09 11:58 UTC, closed without merging